# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'DemoSPM', :git => 'https://github.com/mahi8514/DemoSPM.git'
  # Pods for Example

end
